version: "3.5"

services:
  mysql:
    image: mysql:5.7
    container_name: tcc-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "tcc"
      MYSQL_USER: "tcc"
      MYSQL_PASSWORD: "secret"
      MYSQL_ROOT_PASSWORD: "secret"
    ports:
      - "3306:3306"
    volumes:
      - /var/www/mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    name: tcc-network
    driver: bridge
